### ISSUE TITLE
请问下怎么在小程序中实现啊

### ISSUE THREAD

**Issue by byenic** [243504330/learngit#1]
按照文章提示http://blog.csdn.net/weixin_38608490/article/details/77113216
在小程序中报错了。

var CryptoJS = require("../../utils/aes.js");
------------------------
thirdScriptError
Cannot read property 'createEncryptor' of undefined;at pages/index/index page lifeCycleMethod onLoad function
TypeError: Cannot read property 'createEncryptor' of undefined
    at Object.reset (http://127.0.0.1:9973/appservice/utils/aes.js:516:67)
    at Object.init (http://127.0.0.1:9973/appservice/utils/aes.js:420:18)
    at Object.c.hasOwnProperty.c.init (http://127.0.0.1:9973/appservice/utils/aes.js:19:31)
    at Object.c.hasOwnProperty.c.init (http://127.0.0.1:9973/appservice/utils/aes.js:19:31)
    at Object.c.hasOwnProperty.c.init (http://127.0.0.1:9973/appservice/utils/aes.js:19:31)
    at Object.create (http://127.0.0.1:9973/appservice/utils/aes.js:27:20)
    at Object.createEncryptor (http://127.0.0.1:9973/appservice/utils/aes.js:411:25)
    at Object.encrypt (http://127.0.0.1:9973/appservice/utils/aes.js:566:23)
    at Object.encrypt (http://127.0.0.1:9973/appservice/utils/aes.js:441:59)
    at Encrypt (http://127.0.0.1:9973/appservice/pages/index/index.js:22:36)

是否因为没有引用完全？想请教下，在小程序中如何解决？
非常感谢！我是直接放在小程序的前端了，不知道这样是否可行？

**Comment by 243504330** [comment]
这里是JS的demo， 可能是你有路径问题 没有加载到JS

**Comment by fanguanghui** [comment]
需要加载哪些js？

**Comment by byenic** [comment]
谢谢回复！是的，我也怀疑是路径有问题。我把这三个放在util下面了。
![image](https://user-images.githubusercontent.com/4461680/34408545-76442028-ebff-11e7-967c-edf131e765a8.png)
但是只加载了aes.js，另外两个（mode-ecb.js、pad-nopadding.js）不知道怎么在小程序加载，求助！
![image](https://user-images.githubusercontent.com/4461680/34408563-9b61777a-ebff-11e7-953f-9e3763c46c4c.png)
![image](https://user-images.githubusercontent.com/4461680/34408570-b0c61d96-ebff-11e7-9eab-2ff6a4660310.png)

**Comment by byenic** [comment]
@243504330 求问怎么加载？

@fanguanghui 见图上的三个js

**Comment by 243504330** [comment]
你可以查看一下另外两个js的代码，可以封装在小程序里面  不一定要加载

**Comment by byenic** [comment]
@243504330 多谢多谢！

**Comment by byenic** [comment]
@243504330 为什么程序都一样，但是加密后的结果不同？
![image](https://user-images.githubusercontent.com/4461680/34410523-eba24ab4-ec0b-11e7-8dd3-a3ce69b12a59.png)
![image](https://user-images.githubusercontent.com/4461680/34410532-00298484-ec0c-11e7-8c73-a6bc2494df74.png)

**Comment by hiopro2016** [comment]
@243504330  请问一下， 我在小程序里面引用，发现aes.js文件里面打印CryptoJS对象正常，通过require引用后，输出就不行了，诊断下是啥问题?
![d9d68c68-7f76-48cd-8da1-6ab558728c23](https://user-images.githubusercontent.com/14047657/36710325-3537a7c4-1bb8-11e8-9c7b-04565de50b85.png)
